## Numpy Arrays

Can be 1D vectors or 2D Matrices

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [5]:
#casting a normal python list into an array

np.array(my_list)

array([1, 2, 3])

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [9]:
#creating a matrix using list of lists

my_mat = [[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
# This gives a 2D array

np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Numpy Built-in methods that create arrays faster and simpler

## arange() zeros() ones()

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#Third argument is step size

np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
#1D Vector of zeros - pass a single digit

np.zeros(3)

array([0., 0., 0.])

In [16]:
#2D Matrix of zeros - pass a tuple (row,column)

np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones(4)

array([1., 1., 1., 1.])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Linspace()

In [19]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
np.linspace(0,5,100)

# Identity Matrix Using NumPy

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Arrays of random numbers

In [22]:
np.random.rand(5)   #-Returns 1D 

array([0.05231674, 0.485958  , 0.15657136, 0.13780356, 0.48744207])

In [24]:
np.random.rand(5,5)   # 2D REM: dont pass tuple

array([[0.81862565, 0.86314155, 0.33176065, 0.50811223, 0.11336354],
       [0.43285955, 0.05098377, 0.96620154, 0.89633481, 0.38591032],
       [0.96077664, 0.72285979, 0.98756059, 0.64110676, 0.5569243 ],
       [0.75445947, 0.71390941, 0.35539541, 0.66202766, 0.72097383],
       [0.68332214, 0.83047906, 0.68249074, 0.24221803, 0.21593159]])

A sample from the normal distribution or gaussian distrubution we use randn()

In [25]:
np.random.randn(2)  #1D

array([ 0.29328744, -0.36795179])

In [26]:
np.random.randn(3,3)  #2D

array([[ 0.88849349,  0.58039743,  0.48069432],
       [-0.18035085,  0.28391512,  1.98357571],
       [ 0.0600463 ,  0.39544927,  1.39749574]])

Random integers from a high to low number

In [30]:
#randint(low,high,size)

np.random.randint(1,100)

39

In [31]:
np.random.randint(1,100,10) #inclusive of low end but exclusive of high end

array([81, 27, 46, 86, 36,  3, 42, 16, 39, 15])

# Reshape()

In [34]:
#lets have two arrays

arr = np.arange(0,25)
ranarr = np.random.randint(0,50,10)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
ranarr

array([46, 29, 31, 17, 40,  2, 18,  9, 19, 47])

In [41]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# max() and min()

In [42]:
ranarr.max()

47

In [43]:
ranarr.min()

2

# Location of max and min values

In [44]:
ranarr

array([46, 29, 31, 17, 40,  2, 18,  9, 19, 47])

In [45]:
ranarr.argmax()

9

In [46]:
ranarr.argmin()

5

# Checking the shape

In [47]:
# Checking the SHAPE

arr.shape

(25,)

In [48]:
ranarr.shape

(10,)

In [49]:
arr = arr.reshape(5,5)

In [50]:
arr.shape

(5, 5)

# Checking the data type

In [52]:
arr.dtype   #32 bit integer

dtype('int32')

Instead of typing np.random.randint you can import and make shorter e.g

In [53]:
from numpy.random import randint

randint(2,10,3)

array([9, 8, 3])