# NumPy Indexing and Selection

In [3]:
import numpy as np

In [12]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]

8

In [7]:
#Slicing Notation

arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr[0:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [15]:
#Reset

arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
slice_of_arr = arr[0:6] #Grab everything upto but not including index 6

In [19]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [20]:
slice_of_arr[:] = 99   #grab everything and equate to 99

In [21]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [23]:
#If i call the array now, it actually has changed, not just on the slice

arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Create a copy of original (reference) array to avoid this

In [24]:
arr_copy = arr.copy()

In [25]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
# Now change the copy 

arr_copy[:] = 100

In [28]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [29]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# Indexing a 2D Array

In [31]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [32]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

Two methods of grabbing elements from 2d array
1. Double bracket format
2. Single bracket with comma

In [34]:
#Double Bracket Format

arr_2d[0][0]   # [row][column]

5

In [35]:
arr_2d[0] #returns the first row

array([ 5, 10, 15])

In [36]:
arr_2d[1][1]

25

In [37]:
arr_2d[2][2]

45

In [38]:
#Single Bracket Format

arr_2d[0,0]

5

In [39]:
arr_2d[1,1]

25

In [40]:
arr_2d[2,1]

40

# What if you wanted some matrices from this matrix

In [42]:
arr_2d[:2,1:]
#grab everything upto but not including row 2 and from column 1 onwards

array([[10, 15],
       [25, 30]])

In [43]:
arr_2d[:3,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [44]:
arr_2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [45]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [46]:
arr_2d[1:2]

array([[20, 25, 30]])

In [47]:
arr_2d[0:,1:2]

array([[10],
       [25],
       [40]])

# Conditional selection

In [48]:
arr = np.arange(1,11)

In [49]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
bool_arr = arr > 5

In [54]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [55]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [56]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [57]:
arr[arr<3]

array([1, 2])

In [60]:
arry_2d = np.arange(50).reshape(5,10)

In [61]:
arry_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [63]:
arry_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])